# Generated by Django 5.2.12 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corptools", "0012_corptoolsconfiguration_disable_update_mercenary_tactical_operations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilllist",
            name="category",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
