# Generated by Django 5.2.12 on 2026-08-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corptools", "0130_swap_to_eve_sde"),
        ("corptools", "0013_skilllist_category"),
        ("eve_sde", "0019_alter_dogmaattribute_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JumpCloneImplantSetFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                (
                    "include_active_clone",
                    models.BooleanField(
                        default=True,
                        help_text="Include the active clone implant set in this filter.",
                    ),
                ),
                (
                    "evelocation",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Optionally limit filter to specific structures.",
                        to="corptools.evelocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: Jump Clone Implant Set",
                "verbose_name_plural": "Smart Filter: Jump Clone Implant Set",
            },
        ),
        migrations.CreateModel(
            name="JumpCloneImplantRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Slot 1"),
                            (2, "Slot 2"),
                            (3, "Slot 3"),
                            (4, "Slot 4"),
                            (5, "Slot 5"),
                            (6, "Slot 6"),
                            (7, "Slot 7"),
                            (8, "Slot 8"),
                            (9, "Slot 9"),
                            (10, "Slot 10"),
                        ],
                        help_text=(
                            "All selected implants for this requirement must use "
                            "this implant slot."
                        ),
                    ),
                ),
                (
                    "filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="corptools.jumpcloneimplantsetfilter",
                    ),
                ),
                (
                    "implants",
                    models.ManyToManyField(
                        help_text="Any one selected implant satisfies this slot requirement.",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "ordering": ["slot", "id"],
            },
        ),
    ]
