# Generated by Django 5.2.12 on 2026-08-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corptools", "0013_skilllist_category"),
    ]

    operations = []
