# Generated by Django 5.2.12 on 2026-08-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corptools", "0130_swap_to_eve_sde"),
        ("corptools", "0131_skilllist_category"),
    ]

    operations = []
